### ISSUE TITLE
Could not resolve all files for configuration ':react-native-ux-cam:androidApis'. (0.72.3)

### ISSUE THREAD

**Issue by thisisadarshjais** [uxcam/react-native-ux-cam#100]
I updated my project to React Native 0.72.3 and `react-native-ux-cam": "5.4.8"`

`A build operation failed.
    Could not resolve all files for configuration ':react-native-ux-cam:androidApis'.
Could not resolve all files for configuration ':react-native-ux-cam:androidApis'.
Failed to transform android.jar to match attributes {artifactType=android-mockable-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime, returnDefaultValues=false}.
Execution failed for MockableJarTransform: /Users/adarshjaiswal/Library/Android/sdk/platforms/android-32/android.jar.
Cannot create mockable android.jar
/Users/adarshjaiswal/Library/Android/sdk/platforms/android-32/android.jar`

I tried installation step via 2 way but issue remains the same

1. Via Documentation 

- Went via documentation where it stated just to install the package via npm/yarn. No setup on native side

2. Via Example folder in github 

- Addeed  implementation project(':react-native-ux-cam')
- Added   include ':react-native-ux-cam'
project(':react-native-ux-cam').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-ux-cam/android')

ALSO Do let me know if the documentation is outdated and the step via example folder is correct or vice-versa

**Comment by DFDIEGOH** [comment]
Hey @thisisadarshjais Diego here from the UXCam team - The instructions guides that you will need to follow are listed in this [link](https://developer.uxcam.com/docs/react-native) as well. 

Additionally - Can you share which gradle version you are currently using as well are your compileSDK version in your app?

**Comment by AdarshJais** [comment]
These are the versions, 

`compileSdkVersion = 33`
`distributionUrl=https\://services.gradle.org/distributions/gradle-8.0.1-all.zip`

Yeah, I followed the same link for integration. And as per my understanding, The above-mentioned compileSdkVersion and graded version is the baseline for react native 0.72.3. So can't downgrade that as well.

**Comment by DFDIEGOH** [comment]
Thank you for sharing this information @AdarshJais We will investigate this internally, I will keep you posted on any updates we get on this regard.

**Comment by DFDIEGOH** [comment]
Hey @AdarshJais So we have checked this on our end and RNUXCam version 5.4.8 is working just fine with RN version 0.72.3. 

Did you had a previous version of RN before upgrading your project? We would want to replicate this scenario on our end so sharing as much information as possible will definitely help us in this regard.

**Comment by thisisadarshjais** [comment]
Yes previously I was using `"react-native-ux-cam": "5.3.1"` along with `react-native:"0.67.5"` and then upgraded to `"react-native-ux-cam": "5.4.8"` along with `react-native:"0.72.3"` using this guide ([react-native-helper](https://react-native-community.github.io/upgrade-helper/?from=0.67.5&to=0.72.3))

Let me know what more details can help you, Will try my best to share with you.

**Comment by AdarshJais** [comment]
Please find the repo: https://github.com/AdarshJais/UXCAM_TEST; 

I can see that it can easily be replicated on a fresh project. 

`**react-native-info** `

info Fetching system and libraries information...
System:
  OS: macOS 13.2.1
  CPU: (8) arm64 Apple M2
  Memory: 123.19 MB / 8.00 GB
  Shell:
    version: 5.8.1
    path: /bin/zsh
Binaries:
  Node:
    version: 20.5.0
    path: /opt/homebrew/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.8.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2023.07.24.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods: Not Found
SDKs:
  iOS SDK: Not Found
  Android SDK:
    API Levels:
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
    Build Tools:
      - 21.1.2
      - 23.0.1
      - 23.0.2
      - 23.0.3
      - 24.0.0
      - 24.0.1
      - 24.0.2
      - 25.0.1
      - 25.0.2
      - 26.0.2
      - 26.0.3
      - 27.0.2
      - 27.0.3
      - 28.0.0
      - 28.0.1
      - 28.0.2
      - 28.0.3
      - 29.0.0
      - 29.0.1
      - 29.0.2
      - 29.0.3
      - 30.0.0
      - 30.0.1
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 32.1.0
      - 33.0.0
    System Images:
      - android-31 | Google Play ARM 64 v8a
      - android-33 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.3 AI-223.8836.35.2231.10406996
  Xcode:
    version: /undefined
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/adarshjaiswal/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
  
  
<img width="1295" alt="image" src="https://github.com/uxcam/react-native-ux-cam/assets/40723757/352dc65c-ecac-4fb7-b796-b137678c024e">

**Comment by DFDIEGOH** [comment]
Thank you for sharing more information @AdarshJais and @thisisadarshjais We will investigate this internally, will keep you posted on any further updates in this regard

**Comment by DFDIEGOH** [comment]
Hi @AdarshJais and @thisisadarshjais We have tried this sample project on our end and everything is working as expected. 

You can check the following screenshot: 

```
  "dependencies": {
    "react": "18.2.0",
    "react-native": "0.72.3",
    "react-native-ux-cam": "^5.4.8"
  },
```

<img width="1664" alt="Screenshot 2023-08-09 at 09 35 32" src="https://github.com/uxcam/react-native-ux-cam/assets/22525892/336d7b14-9e6d-4cbc-ae2f-88e3a36a3cb0">

Would it be possible to try the solution that is listed in [here](https://stackoverflow.com/questions/70804827/failed-to-transform-jar-to-match-attributes)?

**Comment by AdarshJais** [comment]
Tried removing the complete cache multiple times, No positive result. 

Is there any possibility that somehow it is related to the below context?

<img width="819" alt="image" src="https://github.com/uxcam/react-native-ux-cam/assets/40723757/9a3d4104-612d-4e78-bbc9-c049010c7a3d">

**Comment by thisisadarshjais** [comment]
Strange but somehow there were difference in the folder structure for the content inside Android-32 as compare to other Android API folders, restructured it same as other and it worked.
