### ISSUE TITLE
[Android] - ANR when app in background

### ISSUE THREAD

**Issue by onmotion** [uxcam/react-native-ux-cam#109]
We have observed periodic ANR errors occurring when the application transitions to the background.

Confirmed on `react-native-ux-cam@5.4.10`

![image](https://github.com/uxcam/react-native-ux-cam/assets/12899080/f57476fe-b1e9-4998-aa97-0589e4a03d46)

**Comment by DFDIEGOH** [comment]
Hi @onmotion - Diego here from UXCam, would it be possible to upgrade to the latest version of the UXCam SDK, version 5.4.12 and check if you are getting the same result?

**Comment by onmotion** [comment]
> Hi @onmotion - Diego here from UXCam, would it be possible to upgrade to the latest version of the UXCam SDK, version 5.4.12 and check if you are getting the same result?

sure, I'll upgrade it for the next release

**Comment by Bishwash-uxcam** [comment]
Hi, @onmotion - What is the value of _timeout-interval-millis_ set for Sentry? Is there any common platform or device where this is happening based on Sentry data?

**Comment by onmotion** [comment]
Hi @Bishwash-uxcam, a default I guess. Cannot found any correlation, OnePlus, OPPO, Infinix, Samsung... But now I look at a stacktrace and nothing related to UXCam there. So probably it's not relevant issue

<img width="592" alt="Screenshot 2023-11-03 at 10 16 34" src="https://github.com/uxcam/react-native-ux-cam/assets/12899080/ca191e1e-658b-4506-8f78-28e8554b1bbb">

**Comment by Bishwash-uxcam** [comment]
Thanks, @onmotion for the confirmation.
We've profiled the main thread usages and found no ANRs. Sentry's default threshold of 5 seconds is much higher than what we regularly test.
We'll close this ticket for now, but feel free to reach out if you encounter any related issues in the future.
