### ISSUE TITLE
linker command failed with exit code 1 (use -v to see invocation

### ISSUE THREAD

**Issue by CrnogoracIvan** [uxcam/react-native-ux-cam#12]
Hi,
regarding to this issue, **we cannot run** iOS in development enviroment **on real device**, but we **can on simulator**. Error is:
`/Build/Products/Debug-iphoneos/UXCam.framework/UXCam(UXCam.o), building for iOS, but linking in object file built for iOS Simulator,`
`/Build/Products/Debug-iphoneos/UXCam.framework/UXCam' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

React Native: 0.63.4
XCode version is 12.3.
UXCam version: 5.3.0

Please help.
Thanks

**Comment by richardgroves** [comment]
Hi @CrnogoracIvan 

Sorry for the problems you are having. Can you try a deep clean - that error message appears to reference the old Framework binary - the new (from SDK wrapper 5.3.0) is an XCFramework.

If a full clean doesn't fix in then try uninstalling and re-installing the UXCam module.

Richard

**Comment by CrnogoracIvan** [comment]
Hi @richardgroves ,

I cleaned project and also delete Derived data folder, but it did not help. Also i delete node modules several times today with no luck to fix issue.
Just to mention one more time, it works on simulator but does not work on device.

**Comment by richardgroves** [comment]
Thanks for the update.

Can you tell me what is in the Pod/UXCam folder?

**Comment by CrnogoracIvan** [comment]
I hope this will help:
<img width="434" alt="Screenshot 2021-01-11 at 18 32 41" src="https://user-images.githubusercontent.com/25108147/104217249-7654ba80-543b-11eb-95ca-4a436ac5aa99.png">

**Comment by richardgroves** [comment]
Ok - that is a snapshot of the finder for the folder ./ios/Pods/UXCam - all looks ok and as expected.

Just to be sure you're not building on an M1 mac are you?

And this breaks doing a build for a specific device or the 'Any iOS' target?

**Comment by CrnogoracIvan** [comment]
If M1 Mac is the latest processor, no I am not buildng on that. And, this breaks when I select my private iPhone device. When I select any simulator everithing works as expected.

**Comment by richardgroves** [comment]
I just made a brand new basic project and added the UXCam module and was able to build and run on simulator and a device.

https://www.dropbox.com/s/g7xpsdxzlijtyyx/AwesomeProject-11Jan21.zip?dl=0 has a zip of that project (needs `npm install`)

My Pods/UXCam folder appears to be the same as yours, so I suspect there is a problem from a previous version hanging around and not getting cleaned. This is a project where you've updated the UXCam SDK version isn't it?


<img width="935" alt="Screenshot 2021-01-11 at 17 49 33" src="https://user-images.githubusercontent.com/715058/104219219-c0d33880-5435-11eb-86c6-32153d273970.png">

**Comment by richardgroves** [comment]
[My app had the 3.3.1 UXCam SDK from `pod update` as that was just released earlier today so the file sizes might be a bit different, but it shouldn't have any impact on building]

**Comment by CrnogoracIvan** [comment]
Just one thing. Today, when I run pod install, this happend: 
Installing RNUxcam (5.3.0)
Installing UXCam (3.3.0)
Is this OK?

**Comment by richardgroves** [comment]
Yep - there is a 3.3.1 but the Cocoapods CDN can take a while to fully distribute it. You can grab the XCFramework for 3.3.1 from https://github.com/uxcam/ios-sdk if you want to force update to 3.3.1 - just expand the XCFramework.zip over the current one in Pods.

**Comment by CrnogoracIvan** [comment]
I fixed issue, after 5 hours of trying. And this is solution:
- Delete node modules
- Delete yarn.lock
- Run yarn install
- Upgraded cocoapods
- Clean pods cache
- Delete pods
- Delete podfile.lock
- Delete XCode derived data
- Unlink react-native-uxcam
- Run pods update
- Run project

If someone see this useful.
Thanks @richardgroves for help.

**Comment by richardgroves** [comment]
Wow! That's a grim list of things to do - thanks for the comprehensive report.

My gut feeling is that the change from .framework to .xcframework is messing up the XCode build system somehow. It feels like it needs a proper uninstall/clean of the old version before adding in the new version. We've seen several problems with XCode 12 crashing and generally not doing the right thing - trying to distribute the SDK with the Swift Package Manager has been full of issues.
