### ISSUE TITLE
Want to add github pages docs

### ISSUE THREAD

**Issue by alexnaiman** [uxcam/react-native-ux-cam#13]
Hello! I started recently using this package, and I thought that it will be useful to create docs with docusaurus and host them on Github pages

I think that it will be easy to found the information regarding the API reference that can only be found by searching through code. I will transform the comments inside [UXCam.js](https://github.com/uxcam/react-native-ux-cam/blob/master/uxcam-react-wrapper/UXCam.js) and create pages, some eventually with useful info from the [Developer Guide](https://help.uxcam.com/hc/en-us/articles/115000966691-React-Native-Integration)

I am creating this issue to ask @uxcam and other maintainers about this idea, to ask about their opinion to check if it is worth trying creating the docs in such a manner, and also for their permission to do so 😄 .

Thanks a lot!

**Comment by richardgroves** [comment]
We have a more top level set of docs on the website at - https://help.uxcam.com/hc/en-us/sections/360003409612-React-Native

The in-code is more for the developer for direct reference. If you think it useful to have a different format then I'd be happy to take a look. I'm not familiar with docusaurus though.
