### ISSUE TITLE
Invalid bitcode error when trying to archive project

### ISSUE THREAD

**Issue by teenoh** [uxcam/react-native-ux-cam#14]
Local builds work well, but when I try archiving a project, I get this error =>

```
ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1200.0.32.29.0_0' Reader: '1103.0.32.62_0')', using libLTO version 'LLVM version 11.0.3, (clang-1103.0.32.62)' for architecture armv7
```

I made some research and found this [this](https://forum.unity.com/threads/ld-could-not-reparse-bitcode-bundle-on-ios-builds.669451/#post-6161593). It seems the library was built with a more recent version of Xcode and as a result can't work for lower versions. 

I am currently using Xcode 11.7 and can't upgrade to 12 at the moment. It will be awesome if there's some other way this could be fixed. Thanks!

React Native version: 0.62.2

**Comment by uxcam-mobile** [comment]
Sorry, but Xcode 12 is needed for the underlying SDK. Also Apple require
you to use XCode 12 for submission from next month -
https://developer.apple.com/ios/submit/

Richard

**Comment by teenoh** [comment]
Thanks for pointing that out. Upgraded to Xcode 12 and it works well now. Thank you 🙌
