### ISSUE TITLE
React native new Arch getting build issues (0.76.0)

### ISSUE THREAD

**Issue by Manikandan-saminathan** [uxcam/react-native-ux-cam#144]
<img width="427" alt="image" src="https://github.com/user-attachments/assets/3ccf7ab6-5658-4216-89f5-36be865f304f">

**Comment by Manikandan-saminathan** [comment]
Duplicate of https://github.com/uxcam/react-native-ux-cam/issues/132

**Comment by gabrieluxcam** [comment]
Hello @Manikandan-saminathan  thanks, we will check this asap.
