### ISSUE TITLE
Invalid Id

### ISSUE THREAD

**Issue by zhahaoyu** [uxcam/react-native-ux-cam#15]
I tried to integrae ux-cam with my project, but I am getting lots of invalid id errors. 

``` E/com.quickapp: No package ID ff found for ID 0xffffffff.
D/ViewRootImpl@706acb7[MainActivity]: ViewPostIme pointer 1
E/com.quickapp: No package ID ff found for ID 0xffffffff.
E/com.quickapp: No package ID ff found for ID 0xffffffff.
D/ViewRootImpl@706acb7[MainActivity]: ViewPostIme pointer 0
D/ViewRootImpl@706acb7[MainActivity]: ViewPostIme pointer 1
E/com.quickapp: No package ID ff found for ID 0xffffffff.
E/com.quickapp: No package ID ff found for ID 0xffffffff.```

Does any one know why?

**Comment by DFDIEGOH** [comment]
Hi there, can you share a little of more information?
- Which version of the SDK are you using?
- Are you trying to implement the SDK on an Android or IOS? If the answer is in both, are you having this issue for both Platforms?

**Comment by zhahaoyu** [comment]
I was using the latest one - 5.3.2
My app runs on both ios and android. the ios one works fine, it is the android version that keeps complaining

**Comment by Anup-UXCam** [comment]
Hi @zhahaoyu do you get this in the newer versions?

**Comment by gabrieluxcam** [comment]
Will be marking this as closed, please make sure to use the latest version of the React Native UXCam SDK. Changelog [here](https://help.uxcam.com/hc/en-us/articles/4404509626509--SDK-UPDATES)
