### ISSUE TITLE
Expose Crash Handling Control Setting

### ISSUE THREAD

**Issue by tomwanzek** [uxcam/react-native-ux-cam#19]
Based on the documentation for the Native Level SDKs, there is a feature set to disable/enable the crash reporting functionality of UXCam: https://help.uxcam.com/hc/en-us/articles/360013231431-Control-Crash-Handling

No corresponding feature is exposed or documented for the React Native layer.

Please expose this feature in the React Native layer of this SDK, so we can utilize it should we need to avoid possible conflicts with another crash reporting solution we are using in our code base.

**Comment by richardgroves** [comment]
@tomwanzek Thanks for bringing that to our attention - I've pushed a fix to the v5/5.3.X branch - once we've tested it we'll do a npm release.

**Comment by richardgroves** [comment]
Version 5.3.3 of the wrapper was just published and includes the `disableCrashHandling` API call and updated Native SDKs.
