### ISSUE TITLE
occludeSensitiveView crashes

### ISSUE THREAD

**Issue by maxoyano** [uxcam/react-native-ux-cam#2]
`
import UXCam from 'react-native-ux-cam';
`

` function hide(ref) {
    UXCam.occludeSensitiveView(ref);
  }`

`
<View ref={hide}>`
       ` <Text style={styles.smallMainTitle}>Hello</Text>`
        ` <Text style={styles.smallMidleTitle}>Hello</Text>`
`</View>`

or 

`<View >`
       ` <Text ref={hide} style={styles.smallMainTitle}>Hello</Text>`
`</View>`

results on

![Captura de Tela 2020-03-24 às 20 37 23](https://user-images.githubusercontent.com/13370870/77486759-53570c80-6e0f-11ea-84a3-49cb2da24c11.png)

**Comment by susanuxcam** [comment]
hey @maxocg I've already shared the solution for this issue [here](https://github.com/negativetwelve/react-native-ux-cam/issues/74). Please, let me know if it works fine now!
