### ISSUE TITLE
Android build fails using Detox and React Native 0.64.2

### ISSUE THREAD

**Issue by antpuleo2586** [uxcam/react-native-ux-cam#24]
When building Android for [Detox test](https://github.com/wix/Detox), there is a failure due to this library's minSdkVersion set at 16, when React Native requires 21+

```

Execution failed for task ':react-native-ux-cam:processDebugAndroidTestManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.facebook.react:react-native:0.64.2] /Users/antoniopuleo/.gradle/caches/transforms-2/files-2.1/4326bd0bd1050879a9023b84d51deec7/jetified-react-native-0.64.2/AndroidManifest.xml as the library might be using APIs not available in 16
        Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 21,
                or use tools:overrideLibrary="com.facebook.react" to force usage (may lead to runtime failures)
```

As per [this comment](https://github.com/wix/Detox/issues/2712#issuecomment-840490767), the recommendation is to update minSdkVersion as follows:

`minSdkVersion rootProject.hasProperty('minSdkVersion') ? rootProject.minSdkVersion : 16`

in the [build.gradle](https://github.com/uxcam/react-native-ux-cam/blob/main/uxcam-react-wrapper/android/build.gradle#L19) file.

Once I do this I then get another error:

```
Error while dexing.
           The dependency contains Java 8 bytecode. Please enable desugaring by adding the following to build.gradle
           android {
               compileOptions {
                   sourceCompatibility 1.8
                   targetCompatibility 1.8
               }
           }
           See https://developer.android.com/studio/write/java8-support.html for details. Alternatively, increase the minSdkVersion to 26 or above.
```

I have previously reported this issue and was told it was fixed:

https://github.com/negativetwelve/react-native-ux-cam/issues/104

I have patched this package locally with these 2 fixes and it now builds successfully, but it might be worth updating for anyone else experiencing this issue.

Component versions:
react-native: 0.64.2
detox: 18.20.0
react-native-ux-cam: 5.3.4-beta.1

Thanks!

**Comment by richardgroves** [comment]
Thanks @antpuleo2586 for the detailed report and fixes. We will investigate internally and come back here if we need more information.

**Comment by dhiraj-uxcam** [comment]
Hello @antpuleo2586, before applying fixes I wanted to reproduce the issue on my side. I tried [Detox React Native Demo](https://github.com/wix/Detox/tree/master/examples/demo-react-native) (updated component versions) but could not reproduce the issue.

It would be great if you could check [demo](https://github.com/wix/Detox/tree/master/examples/demo-react-native) project and share if there is any difference or share any further info that helps us to replicate the issue.

Thanks!

**Comment by raldred** [comment]
We have forked this, the minSDK for RN 64.2 is 21.
https://github.com/residently/react-native-ux-cam/commit/4eab3d9cc7f82ba433b6f13b35e59a199b506c7a

**Comment by Jawkx** [comment]
@antpuleo2586 

Like what @mikehardy  said [here](https://github.com/wix/Detox/issues/2712#issuecomment-865227658), just DIY it.
add this inside the `subprojects{` in your `android/build.gradle` file. Or else you will have to one by one asking the library maintainer to change their minSdkVersion which is not really optimal.

```
subprojects { 
    ...

    afterEvaluate { subproject ->
        if((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
                defaultConfig {
                    minSdkVersion rootProject.ext.minSdkVersion
                    targetSdkVersion rootProject.ext.targetSdkVersion
                }
            }
        }
    }
}
```

**Comment by mushtaque87** [comment]
I tried this command and the build Passed 

cd android ; ./gradlew app:assembleRelease app:assembleAndroidTest -DtestBuildType=release ; cd -

Do the same for debug build. Add `app` before `assembleRelease` and `assembleAndroidTest`
