### ISSUE TITLE
Recording specific screen

### ISSUE THREAD

**Issue by MateuszRostkowski** [uxcam/react-native-ux-cam#25]
Hi is there any solution that can help me recording current screen. I'm using this setup:

When mounting screen I'm starting recording, and on unmount I'm stoping recording
```js
useEffect(() => {
  if (isFocused) {
    // Start recording on mount
    UXCam.startWithKey("UXCAM_KEY")

    // Stop recording on unmount
    return () => {
      UXCam.stopSessionAndUploadData()
    }
  }
}, [isFocused])
```
  
This setup was working fine while testing but when we go live this is not working for most of the users, UXCam is recording everything in the app 😓

The business need is to record only one screen in app without other screens.

**Comment by DFDIEGOH** [comment]
Hi @MateuszRostkowski I just sent you a message, it should have reached by now.  We can continue our conversation over there. 

Please let me know if you need anything else.

**Comment by abhayrajput87** [comment]
@DFDIEGOH @MateuszRostkowski  am still facing this issue. Have you guys found any solution for it?
