### ISSUE TITLE
framework not found UXCam

### ISSUE THREAD

**Issue by dameunbite** [uxcam/react-native-ux-cam#30]
Hi, we are trying to install UXCam to our app but XCode throws the following error "framework not found UXCam". I can see de pod in the pods folder inside the ios folder.

I followed this guide to make the installation and it did not worker: https://help.uxcam.com/hc/en-us/articles/115000966691-React-Native-Integration

I also tried the IOS manual installation and it did not worked. How can I fix this?

<img width="561" alt="Screen Shot 2021-11-10 at 12 23 43 PM" src="https://user-images.githubusercontent.com/48269003/141151922-e7a24b0d-b358-4523-887e-44dedb3faec3.png">

Pod installation process:
1- cd ios
2- pod install
3- pod update

Node version: 14.17.4
NPM Version: 7.20.5

Package.json
```
    "react": "17.0.2",
    "react-native": "0.66.1",
    "react-native-ux-cam": "5.3.3"
```

**Comment by DFDIEGOH** [comment]
Hi @dameunbite I have contacted you via email.

Did you get the opportunity to check it? 

Please keep in mind that in order for the latest version of our SDK to work properly you will need to have XCode version 12.4 or higher as well as Cocoapods version 1.10 or higher.

**Comment by dameunbite** [comment]
Will continue conversation via email

**Comment by dameunbite** [comment]
In case someone goes into the same trouble.

The problem was that in Xcode project Framework Search Paths debug mode did not have UXCam but in Release it was present.
I just had to add the UXCam framework to debug mode and that fixed the problem

Here is an image of mode release: (correct way)

![Screen Shot 2021-11-22 at 7 49 55 PM](https://user-images.githubusercontent.com/48269003/142954741-e1421ffe-6fcb-4031-97f2-cce8e50e6e4f.png)
