### ISSUE TITLE
Panresponder - broken - IOS

### ISSUE THREAD

**Issue by 0hio-creator** [uxcam/react-native-ux-cam#34]
When i have this library running with another library that uses panresponder in my case a slider library
https://github.com/ptomasroos/react-native-multi-slider

The animations break and become very jerky only moving a few cm before stopping. 

I'm guessing with how recording gestures are handled they are altering how they can be interacted with.

The Panresponder piece is what I think is broken which is what is driving the slider. When I try just a simple drag a square around animation with pain responder I get similarly janky behaviour, Thread with an example of the janky drag animation,
https://stackoverflow.com/questions/55258808/react-native-panresponder-animation-not-working-on-ios

**Comment by richardgroves** [comment]
Hi @0hio-creator 

Sorry to hear you are having problems. Can you try this method:
```
/** 
        Enable/Disable advanced gesture recognition like swipe and pinch gestures.
        @param enable Set `true` to enable or `false` to disable before `startWithKey`. Default is `true`.
        @note Disable this on iOS if you are having problems with swipes or other gestures being interrupted while recording sessions.
    */
    static enableAdvancedGestureRecognizers(enable){
        if (platformIOS){
            UXCamBridge.enableAdvancedGestureRecognizers(enable);
        }
    }
```
With `false` for the enable flag - call it before the call to `startWithKey`.

What this does is disable some of UXCam's gesture handling so that 3rd party libraries that aren't built for co-operative gesture handling can work as they expect. You lose some fidelity in the gesture recording of the session, but the user experience should go back to normal.

Richard

**Comment by 0hio-creator** [comment]
@richardgroves Where do I add this code?

I don't think you can have co-operative third party libraries.
UX-cam does not work with the official docs for panresponder. See the example I can't get that to work with UX-cam on.

https://reactnative.dev/docs/panresponder

**Comment by DFDIEGOH** [comment]
Hi @0hio-creator You should add the following code before the startWithKey method: 

UXCam. enableAdvancedGestureRecognizers(false) 

And that should do the trick, please let me know if there is anything else I can do for you.

**Comment by cameronnapoli** [comment]
I just wasted probably a total of 15 hours looking for this. I thought it was a bug in my application.

I **very strongly** feel that `enableAdvancedGestureRecognizers` should default to false.

**Comment by Anup-UXCam** [comment]
Hi @cameronnapoli , your feedback has been noted, thanks.
