### ISSUE TITLE
iOS: RNUxcam.occludeSensitiveScreen was called with 2 arguments but expects 1 arguments.

### ISSUE THREAD

**Issue by lha-ryq** [uxcam/react-native-ux-cam#37]
On iOS I am not able to use `RNUxcam.occludeSensitiveScreen` as it causes the crash:

![Simulator Screen Shot - iPhone 13 - 2022-01-31 at 19 12 29](https://user-images.githubusercontent.com/16624100/151849626-81f4e615-ed76-4f86-a350-9f6aa3d4c7d5.png)

I tried to integrate and update the UXCam framework a couple of times, but it did not fix the problem. It looks like there is an incompatibility between JS and native code in UXCam dependency.

Usage:
```js
import RNUxcam from 'react-native-ux-cam'

const signIn = async () => {
  RNUxcam.occludeSensitiveScreen(true)
  ...
  ...
  RNUxcam.occludeSensitiveScreen(false)
}
```

Environment:
Xcode: 13.2.1

packages.json:
"react-native": "0.66.4",
"react-native-ux-cam": "^5.3.4"

Podfile.lock:
```
- RNUxcam (5.3.4):
    - React-Core
    - UXCam (~> 3.3.9)
```

**Comment by lha-ryq** [comment]
I was able to fix this issue by changing the code in `node_modules/react-native-ux-cam/UXCam.js`

Original:
```js
    static occludeSensitiveScreen(hideScreen, hideGesture) {
        if(typeof hideGesture !== "undefined"){
            UXCamBridge.occludeSensitiveScreen(hideScreen, hideGesture);
        }else{
            UXCamBridge.occludeSensitiveScreen(hideScreen, true);
        }
    }
```

Updated:
```js
    static occludeSensitiveScreen(hideScreen, hideGesture) {
        UXCamBridge.occludeSensitiveScreen(hideScreen);
    }
```

**Comment by DFDIEGOH** [comment]
Hi @lha-ryq I hope this finds you well.

I can see that you are trying to hide a specific screen and unhide it using the following:

```
const signIn = async () => {
  RNUxcam.occludeSensitiveScreen(true)
  ...
  ...
  RNUxcam.occludeSensitiveScreen(false)
}

```
Would it be possible if you can share the scenarios where this methods are being called? Do they need to meet specific requirements? Just to make sure that both of the method are not being called at the same time. 

Also, you mentioned in the same thread that after doing some changes everything is working just fine, is this still the case?

Please make sure that you would need to call the method  `RNUxcam.occludeSensitiveScreen(true)` for the screen that you would want to hide from the recording and right before the user enters this screen and RNUxcam.occludeSensitiveScreen(false) when the user leaves this specific screen. 

Another workaround would be to use the specific flag from the dashboard to omit the specific screen that you want to hide or to omit from the recording. 

Please let me know.
