### ISSUE TITLE
[Android] NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by Ramanpreet6262** [uxcam/react-native-ux-cam#62]
### NullPointerException: Attempt to get length of null array

**Version Info:**
`react-native-ux-cam: 5.3.4`
`react-native: 0.66.4`

**Error Stack Trace (Reported on sentry):**
```
java.lang.NullPointerException: Attempt to get length of null array
    at com.uxcam.internals.ci.a
    at com.uxcam.internals.cn$2.onResponse
    at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:919)
```

**Comment by gabmadera** [comment]
Hi @Ramanpreet6262 would it be possible to upgrade to the latest version (`react-native-ux-cam: 5.4.0`) and check if the error still persists? 

Here's the [documentation](https://developer.uxcam.com/docs/react-native) for the slighlty different initialisation of the SDK in this version.

**Comment by gabrieluxcam** [comment]
Closing this, pelase always make sure to use the latest SDK version, change log is available [here](https://help.uxcam.com/hc/en-us/articles/4404509626509--SDK-UPDATES)
