### ISSUE TITLE
uxcam react native Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'android.graphics.Canvas android.view.Surface.lockCanvas(android.graphics.Rect)' on a null object reference

### ISSUE THREAD

**Issue by rohit-daffodil** [uxcam/react-native-ux-cam#63]
We are getting the crashes 4-5 times with 100 users  in a day on production users. Please find below full trace.

"react-native": "0.66.4",
"react-native-ux-cam": "^5.4.0",

com.uxcam.internals.gs$ad.a (SourceFile:24)
com.uxcam.internals.gs$ad.a (SourceFile:16)
com.uxcam.internals.gs$ad.lambda$6JKlk2XJVUgCouwtk1iq13kgz64
com.uxcam.internals.-$$Lambda$gs$ad$6JKlk2XJVUgCouwtk1iq13kgz64.a (Unknown Source:4)
com.uxcam.internals.fm.a (SourceFile:51)
com.uxcam.internals.-$$Lambda$qf4WIVmP0YNDPt9j_9Ft1_pW5fI.a (Unknown Source:2)
com.uxcam.internals.fm.a (SourceFile:318)
com.uxcam.internals.-$$Lambda$_9mE2021CHomlVng0dy_9It_CEg.a (Unknown Source:11)
com.uxcam.internals.fu.a (SourceFile:54)
com.uxcam.internals.fu.lambda$_yzMV-E4tTqP5srseEI0KK6ea5I
com.uxcam.internals.-$$Lambda$fu$_yzMV-E4tTqP5srseEI0KK6ea5I.run (Unknown Source:10)

Any help in this regard will be highly appreciable.

**Comment by rohit-daffodil** [comment]
Dear Team, any updates over here. We have to puase using uxcam due to this issue?

**Comment by DFDIEGOH** [comment]
Hi @rohit-daffodil Diego here from the UXCam team! I apologize for the inconvenience in this regard! 

The team is already aware of this crash and we are currently working on it. We will be releasing a new version of our React Native SDK as soon as this gets fixed, but I will keep you posted as soon as we release this on our end. 

I appreciate your patience in this regard, but please let me know if you have further questions in here

**Comment by rohit-daffodil** [comment]
Thanks a lot Diego

Any expected timeline for resolving this issue?. I will be glad to use this
after crash resolved

Best Regards,

Rohit Bansal | Senior Manager - IT

Daffodil Software Pvt. Ltd.
Winner of Deloitte Tech Fast 50 India


IMPORTANT: This email and any attachments to it are confidential and
intended solely for the use of the person to whom they are addressed. Any
unauthorized use, dissemination of the information, or copying of this
message is prohibited. If you are not the addressee please notify the
sender immediately by return email and delete this message.

**Comment by uchitsingh-dojo** [comment]
Getting similar crash when using UXCam Android SDK - 3.4.3@aar. Posting here as i cannot find the repository for uxcam android sdk. 


`Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'android.graphics.Canvas android.view.Surface.lockCanvas(android.graphics.Rect)' on a null object reference

com.uxcam.internals.gs$ad.a (gs.java:16)
com.uxcam.internals.gs$ad.$r8$lambda$6JKlk2XJVUgCouwtk1iq13kgz64 (gs.java)
com.uxcam.internals.gs$ad.$r8$lambda$6JKlk2XJVUgCouwtk1iq13kgz64 (gs.java)
com.uxcam.internals.gs$ad$$InternalSyntheticLambda$0$fdac19f8126774028461e6366a023f325bb71a9c71ca08b77c9ca1db2103ae77$0.a (gs.java:6)
com.uxcam.internals.fm.a (fm.java:9)
androidx.fragment.app.FragmentKt$$ExternalSyntheticLambda0.a (R8$$SyntheticClass:4)
com.uxcam.internals.fm.a (fm.java:8)
com.uxcam.internals.fm$$InternalSyntheticLambda$0$374430e1ed92aad81e893e282514aef41d6ef567c324aeab25f273f6c1bb3d2c$0.a (fm.java:11)
com.uxcam.internals.fu.a (fu.java:54)
com.uxcam.internals.fu.$r8$lambda$_yzMV-E4tTqP5srseEI0KK6ea5I (fu.java)
com.uxcam.internals.fu$$InternalSyntheticLambda$0$51c3431cef342fa63951966a5b86019c182f945eb9cfc0ecc59bec81d7297593$0.run (fu.java:10)
android.os.Handler.handleCallback (Handler.java:873)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:193)
android.app.ActivityThread.main (ActivityThread.java:6846)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:883)
`

**Comment by DFDIEGOH** [comment]
Hi @uchitsingh7 I apologize for the inconvenience, we just released a new version for our Android SDK that is version 3.4.4. This should fix this crash that you are reporting in here. 

For the React Native Fix - we will releasing a new version in the next couple of days, so I will keep you posted on this as well. @rohit-daffodil

**Comment by rohit-daffodil** [comment]
Hey Team

As the issue fixed in native library, by when we can expect a new react native npm update ?

**Comment by gabmadera** [comment]
@rohit-daffodil Hello there, it has been released now on version 5.4.2, you can upgrade the SDK and check the change log here: https://help.uxcam.com/hc/en-us/articles/4404509626509--SDK-UPDATES
