### ISSUE TITLE
Cannot read properties of undefined (reading 'optIntoSchematicRecordings')

### ISSUE THREAD

**Issue by izaakrogan** [uxcam/react-native-ux-cam#67]
Hi there,

I am getting an error:

`cannot read properties of undefined (reading 'optIntoSchematicRecordings').`

I'm running:

`expo@46.0.7`
`react-native-ux-cam@5.4.2`

Could be related to: #28 

Thanks!

**Comment by ahsanparacha02** [comment]
getting same issue and also ios build failed in latest version, @izaakrogan did u get any solution ?

**Comment by DFDIEGOH** [comment]
Hi @izaakrogan and @ahsanparacha02 We can see that this problem happens when you have Expo integrated in your application. In order to do this, you will need to follow the instructions listed in here: https://developer.uxcam.com/docs/expo

Please let us know in case you have further questions

**Comment by DFDIEGOH** [comment]
Hi @ahsanparacha02 and @izaakrogan Just checking in - Did you get the opportunity to check this on your end? Please let us know

**Comment by tomruijgrok** [comment]
I am running into this error as well. I'm running:
`react-native@0.68.2` 
`react-native-ux-cam@5.4.5`

I've followed the docs (just copy paste a few lines of code and inserted my api key) and then my app when start.

edit: I'm not using expo

**Comment by rojen-kic** [comment]
@tomruijgrok Did you got any solution? I too am having same issue.

**Comment by ahsanparacha02** [comment]
> @tomruijgrok Did you got any solution? I too am having same issue.

Try v5.4.0, working fine on my end

**Comment by tomruijgrok** [comment]
Downgrading to v5.4.0 doesn't work unfortunately. No solution yet

**Comment by rojen-kic** [comment]
> Downgrading to v5.4.0 doesn't work unfortunately. No solution yet

Worked after following this step (for IOS):
1. Navigate inside ios directory
2. Pod deintegrate 
3. Pod install

`react-native@0.66.5`
`react-native-ux-cam@5.4.5`

**Comment by tomruijgrok** [comment]
> > Downgrading to v5.4.0 doesn't work unfortunately. No solution yet
> 
> Worked after following this step (for IOS):
> 
> 1. Navigate inside ios directory
> 2. Pod deintegrate
> 3. Pod install
> 
> `react-native@0.66.5` `react-native-ux-cam@5.4.5`

This did the trick! I followed the [instructions](https://developer.uxcam.com/docs/react-native) on the uxcam website. There is no mention of having to install pods again. In hindsight I could have known myself. Maybe it's a good idea to mention this on the website aswell? 

Thanks for your help anyways @rojen-kic

**Comment by gabrieluxcam** [comment]
Closing this, please always make sure to use the latest SDK version, change log is available [here](https://help.uxcam.com/hc/en-us/articles/4404509626509--SDK-UPDATES)
