### ISSUE TITLE
Android JCenter dependency

### ISSUE THREAD

**Issue by kfitzsimons** [uxcam/react-native-ux-cam#68]
Hi

JCenter went down today, it has been 'sunset' as of last year from what I've scanned over.

Please can you change to another source like Maven?
This would like prevent apps from building.

Failed build logs below (Android, react-native-ux-cam v5.3.3, looks like same for latest version)

----
* What went wrong:
A problem occurred configuring project ':react-native-ux-cam'.
> Could not resolve all artifacts for configuration ':react-native-ux-cam:classpath'.
   > Could not resolve com.android.tools.build:gradle:2.3.1.
     Required by:
         project :react-native-ux-cam
      > Could not resolve com.android.tools.build:gradle:2.3.1.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.1/gradle-2.3.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.1/gradle-2.3.1.pom'.
               > Read timed out
---

Thanks

**Comment by gabmadera** [comment]
Hey @kfitzsimons thanks for reaching out, 

it seems it may be an issue with the jcenter repository on Android side, so I'd like to suggest a temporary test to build your app, could you please take this approach:

In `android/build.gradle`, add the following at the top in `allprojects` -> `repositories`.

It will remove `jcenter()` from all the dependencies during config phase and replace it with `mavenCentral()`.

It should look something like this:

```
allprojects { 
repositories {
all { ArtifactRepository repo -> 
println repo.url.toString() 
if (repo.url.toString().startsWith("https://jcenter.bintray.com/")) { 
project.logger.warn "Repository ${repo.url} removed." 
remove repo 
mavenCentral() 
}
} 
...other repos 
} 
}
```

Please, do let me know if it helps!

**Comment by gabrieluxcam** [comment]
This dependency has already been removed on the latest UXCam SDK version, 5.4.8. Please let us know if anything, I will be closing this ticket but don't hesitate to reach out in any case. @kfitzsimons
