### ISSUE TITLE
Random crash with ux cam (cipher not initialized)

### ISSUE THREAD

**Issue by 3KINGZ** [uxcam/react-native-ux-cam#72]
this issue tends to happen at random and it's only experienced on android

![Screenshot_20221123-084621](https://user-images.githubusercontent.com/36764715/203949455-60602da4-4c1c-4402-a99b-e3ffcb45fdfc.png)

**Comment by DFDIEGOH** [comment]
Hi @3KINGZ I just wanted to share that our latest version is 5.4.3 for our React Native SDK. Can you share which version you currently have, as well as the frequency and Android models that are affected by this?

**Comment by 3KINGZ** [comment]
> Hi @3KINGZ I just wanted to share that our latest version is 5.4.3 for our React Native SDK. Can you share which version you currently have, as well as the frequency and Android models that are affected by this?

@DFDIEGOH the version we are currently using is 5.3.4, it happens at random and on different android models(not dependant on version or model)

**Comment by DFDIEGOH** [comment]
Thank you for sharing this @3KINGZ This error has already been fixed in latest version of our UXCam package, so it will be extremely helpful if you can upgrade to latest version 5.4.3 and confirm if behaviour is now corrected.

**Comment by gabrieluxcam** [comment]
Closing this, please always make sure to use the latest SDK version, change log is available [here](https://help.uxcam.com/hc/en-us/articles/4404509626509--SDK-UPDATES)
