### ISSUE TITLE
Pod not installed successfully

### ISSUE THREAD

**Issue by Bhautik58** [uxcam/react-native-ux-cam#76]
React-Native : 0.64.3
react-native-ux-cam : 5.4.2

i am getting following error when i installing pod.

<img width="1150" alt="Screenshot 2022-12-15 at 7 22 50 PM" src="https://user-images.githubusercontent.com/53619727/207876157-55714ca5-5e24-4b87-9110-c445dc9e1c4b.png">

**Comment by gabrieluxcam** [comment]
Hello @Bhautik58  apologies for the delayed response, we're working on improving reply times on Github. 

Have you tried going to your ios folder and perform a pod install --repo-update?

Additionally, we suggest upgrading React Native versions to be able to use the latest SDK versions, which depend on updated native libraries. 

Thanks!

**Comment by DFDIEGOH** [comment]
Close due to inactivity
