### ISSUE TITLE
Logs from Javascript are not visible in Logs Tab

### ISSUE THREAD

**Issue by Aximem** [uxcam/react-native-ux-cam#78]
After enabling "Record app logs" in our App Settings we are only able to see "native logs", the logs from Javascript (e.g.: `2023-01-11 11:18:34.385955+0100 XXXXX[3952:372638] [javascript] initConnection`) are not visible.

**Comment by gabrieluxcam** [comment]
Hello @Aximem  apologies for the delayed response. 

Indeed, Javascript logs do not currently show in the app logs feature, only native ones. Our team will work in the near future to be able to capture all kind of logs from these frameworks. Thanks and apologies!
