### ISSUE TITLE
Loss of event on swipe

### ISSUE THREAD

**Issue by oarsheo** [uxcam/react-native-ux-cam#8]
1.When the plugin is enabled, swipes do not work correctly.
Loss of event on swipe PanResponder.onPanResponderRelease

2. There is a problem of indentation on android
![image](https://user-images.githubusercontent.com/26067179/99278529-d530f580-2837-11eb-8ad9-0ee6f2024bb3.png)

**Comment by susanuxcam** [comment]
Hey @oarsheo! Is the 1st issue happening on Android or iOS? As for the 2nd one, could you tell us what exactly you mean by the indentation problem?

**Comment by oarsheo** [comment]
> Hey @oarsheo! Is the 1st issue happening on Android or iOS? As for the 2nd one, could you tell us what exactly you mean by the indentation problem?

1. 1st issue happening on iOS 
the swipe stops working because it prematurely fulfills the PanResponder.onPanResponderRelease callback

2. indentation for the statusbar is added on android

**Comment by susanuxcam** [comment]
Hey @oarsheo, as for the first issue, can you check this section and follow this solution: https://help.uxcam.com/hc/en-us/articles/360020821551-We-are-seeing-issues-with-the-taps-swipes-upon-implementing-UXCam-SDK-on-React-Native?

As for the 2nd case, can you share replication steps or a sample app with this issue? We haven't seen anything like this before and it would be difficult to replicate it in our environment without additional information

**Comment by oarsheo** [comment]
![image](https://user-images.githubusercontent.com/26067179/99967803-fe560680-2da0-11eb-8077-cdbd91e784bb.png)
Doesn't work Tried to rebuild the project, cleaned, reinstalled, etc.

**Comment by susanuxcam** [comment]
hey again @oarsheo,

In the file node_modules/react-native-gesture-handler/ios/RNGestureHandlerManager.m - Could you add:

// UXCam
	if (gestureRecognizer.cancelsTouchesInView == NO)
	{
		return;
	}

above
UIView *parent = rootContentView.superview;

? Please, let me know if it helped!

**Comment by oarsheo** [comment]
> hey again @oarsheo,
> 
> In the file node_modules/react-native-gesture-handler/ios/RNGestureHandlerManager.m - Could you add:
> 
> // UXCam
> if (gestureRecognizer.cancelsTouchesInView == NO)
> {
> return;
> }
> 
> above
> UIView *parent = rootContentView.superview;
> 
> ? Please, let me know if it helped!

Thanks, all is work

**Comment by susanuxcam** [comment]
thanks for letting us know!
