### ISSUE TITLE
Cannot read property 'startWithConfiguration' of null' in uxcam

### ISSUE THREAD

**Issue by vikasattri** [uxcam/react-native-ux-cam#83]
<img width="321" alt="Screenshot 2023-03-17 at 11 55 30 AM" src="https://user-images.githubusercontent.com/38360084/225836381-cd6de2a5-ad56-49dd-88fa-0d4e27b5c456.png">
 ERROR  TypeError: Cannot read property 'startWithConfiguration' of null

This error is located at:
    in App (created by ExpoRoot)
    in ExpoRoot
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes

**Comment by DFDIEGOH** [comment]
Hi @vikasattri I apologize for the delay in this regard. 

Quick question - Are you trying to integrate UXCam in your Expo application? If yes, are you following the instructions that are listed in here: https://developer.uxcam.com/docs/expo?

**Comment by gabrieluxcam** [comment]
Closing this, please always make sure to use the latest SDK version, change log is available [here](https://help.uxcam.com/hc/en-us/articles/4404509626509--SDK-UPDATES)
