### ISSUE TITLE
Build error |  Could not find com.uxcam:uxcam:3.6.0

### ISSUE THREAD

**Issue by omerts** [uxcam/react-native-ux-cam#87]
Hi, 

Added the library like in the docs, and getting the following error:

```
Could not determine the dependencies of task ':app:processDebugResources'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.uxcam:uxcam:3.6.0.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/com/uxcam/uxcam/3.6.0/uxcam-3.6.0.pom
       - https://repo.maven.apache.org/maven2/com/uxcam/uxcam/3.6.0/uxcam-3.6.0.pom
       - file:/C:/development/mobile-app/node_modules/jsc-android/dist/com/uxcam/uxcam/3.6.0/uxcam-3.6.0.pom
       - https://dl.google.com/dl/android/maven2/com/uxcam/uxcam/3.6.0/uxcam-3.6.0.pom
       - https://www.jitpack.io/com/uxcam/uxcam/3.6.0/uxcam-3.6.0.pom
     Required by:
         project :app > project :react-native-ux-cam

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

```

**Comment by omerts** [comment]
I solved it by adding the following to build.gradle:
```
allprojects {
    repositories {
        maven{ 
            url 'https://sdk.uxcam.com/android/' 
        } 
    }
}
```
But this is not documented anywhere in relation to react native only android sdk.

**Comment by gabrieluxcam** [comment]
Hello @omerts  apologies for the delayed response. 

We've updated our SDK to avoid any inconsistencies when building and will update our docs accordingly. 

I'll be closing this, please always make sure to use the latest SDK version, change log is available [here](https://help.uxcam.com/hc/en-us/articles/4404509626509--SDK-UPDATES)

**Comment by Srpalkn** [comment]
> Hello @omerts apologies for the delayed response.
> 
> We've updated our SDK to avoid any inconsistencies when building and will update our docs accordingly.
> 
> I'll be closing this, please always make sure to use the latest SDK version, change log is available [here](https://help.uxcam.com/hc/en-us/articles/4404509626509--SDK-UPDATES)

I still get the same error with SDK update. @gabrieluxcam 

<img width="1424" alt="Screenshot 2023-08-01 at 16 34 11" src="https://github.com/uxcam/react-native-ux-cam/assets/121541133/05b52c15-4046-46b9-9f3f-c65de5e82aad">

**Comment by chukwudibarrah** [comment]
> I solved it by adding the following to build.gradle:
> 
> ```
> allprojects {
>     repositories {
>         maven{ 
>             url 'https://sdk.uxcam.com/android/' 
>         } 
>     }
> }
> ```
> 
> But this is not documented anywhere in relation to react native only android sdk.

This solved the issue for me in 2025. Thank you!
