### ISSUE TITLE
Is it possible to use this library without Expo EAS builds?

### ISSUE THREAD

**Issue by ghmendonca** [uxcam/react-native-ux-cam#91]
Right now I'm not using Expo EAS builds, I'm using Expo Go for development, and expo updates to publish changes. I wonder if it's possible to use UXCam without having to use EAS build.

I've tried adding the config to my app, but I always get the error:

`TypeError: Cannot read property 'startWithConfiguration' of null`

And my config:

```
RNUxcam.optIntoSchematicRecordings();
const configuration = {
  userAppKey: process.env.UXCAM_APP_KEY,
  enableAutomaticScreenNameTagging: false,
  enableImprovedScreenCapture: true,
};
RNUxcam.startWithConfiguration(configuration);
```

**Comment by gabrieluxcam** [comment]
Hello @ghmendonca  unfortunately it is not currently possible as Expo does not support native modules, thus you'll need to do so with EAS, [here's](https://developer.uxcam.com/docs/expo) the reference just in case. Thanks!
